Bluetooth: Fix build if CONFIG_BLUETOOTH_DEBUG_HCI_CORE is enabled
If CONFIG_BLUETOOTH_DEBUG_HCI_CORE is enabled it causes the following
error:

hci_core.c:514:12: error: 'struct bt_hci_evt_encrypt_key_refresh_complete' has no member named 'encrypt'
         evt->encrypt);
            ^

Change-Id: I1983653eba40b9aea6b19572b39a285883f00450
Signed-off-by: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>